INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("example", "category", 100, "DEC 29TH", "JAN 1ST");

INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);
INSERT INTO users (name, age) VALUES ("Brad", 25);

INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 1, 1);
