INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);
INSERT INTO users (name, age) VALUES ("Michael", 23);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("league", "games", 200, 1994-08-29, 2018-06-13);

INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 3);
